In [39]:
import pandas as pd

In [40]:
prompts = pd.read_csv('../data/prompts.csv')
template_statements = pd.read_excel('../data/templates.xlsx', sheet_name='Statements')
template_terms = pd.read_excel('../data/templates.xlsx', sheet_name='Terms')
template_topics = pd.read_excel('../data/templates.xlsx', sheet_name='Topics')

In [41]:
prompts.head()

                                              prompt
0  I want to write an article about: "Common fair...
1  I want to write an article about: "Machine Lea...
2  I want to write an article about: "Evaluation ...
3  I want to write an article about: "Benchmark c...
4  I want to write an article about: "Word embedd...

In [42]:
template_statements.head()

,ID,MAIN STATEMENT,DETAILED STATEMENT,REFERENCE,ID_specific_topic,ID_specific_topic_2,Encargada,Articulo Esther asociado
0,1,Common fairness definitions are mathematically...,NaN,https://papers.nips.cc/paper_files/paper/2017/...,1,NaN,Melissa,NaN
1,2,Machine Learning models can be biased even wit...,Seeamingly neutral features can act as proxies...,NaN,1,NaN,Melissa,NaN
2,3,Evaluation and mitigation efforts that define ...,Fairness-related failures can come from the su...,doi.org/10.1145/3287560.3287598,1,NaN,Melissa,NaN
3,4,Benchmark choices for GenAI models reflect the...,"When benchmarks are US-centric, they can syste...",https://doi.org/10.1609/aies.v8i3.36707,1,NaN,Melissa,NaN
4,5,Word embeddings can encode gender stereotypes ...,"Even when trained on large, widely used corpor...",NaN,2,NaN,Melissa,NaN

In [43]:
template_terms.head()

,ID,TERM,REFERENCE,ID_specific_topic
0,1,Fairnes through unawareness,NaN,1
1,2,Selective labels problem,barocas - agregar,1
2,3,Equalized Odds,"[""Moritz Hardt, Eric Price, and Nathan Srebro....",2
3,4,Equal opportunity,"[""Moritz Hardt, Eric Price, and Nathan Srebro....",2
4,5,Demographic Parity,NaN,2

In [44]:
def assign_topic_term(prompt):
    for i, row in template_terms.iterrows():
        if row.TERM in prompt and "Define" in prompt:
            return str(row.ID_specific_topic)
    
prompts['topic'] = prompts.prompt.apply(assign_topic_term)

In [45]:
def assign_topic_statement(prompt):
    for i, row in template_statements.iterrows():
        if row['MAIN STATEMENT'] in prompt:
            topic = str(row.ID_specific_topic)
            if not pd.isna(row['ID_specific_topic_2']):
                topic += '-' +  str(row['ID_specific_topic_2'])
            return topic

prompts.loc[prompts.topic.isna(), 'topic'] = prompts[prompts.topic.isna()].prompt.apply(assign_topic_statement)

In [52]:
prompts.to_csv('../data/prompts_topic.csv', index = None)